Repository elastic/ecs-logging-python, pull requests merged in 2021-07, with the labels that each got.

#46 Fix merging dicts for duplicate dotted keys
  CHANGELOG.md
  ecs_logging/_structlog.py
  ecs_logging/_utils.py
  tests/conftest.py
  tests/test_apm.py
  tests/test_structlog_formatter.py
Labels: agent-python

#47 Add default/fallback behavior for json.dumps
  .pre-commit-config.yaml
  CHANGELOG.md
  ecs_logging/_utils.py
  tests/test_structlog_formatter.py
Labels: agent-python

#49 [CI] Run pipeline on daily basis if master branch
  .ci/Jenkinsfile
Labels: Team:Automation, agent-python, automation

#50 Rev to v1.0.1
  CHANGELOG.md
  ecs_logging/__init__.py
Labels: agent-python

#51 synchronize ecs-logging spec
  tests/resources/spec.json
Labels: agent-python, automation
