Repository elastic/ecs-logging-python, pull requests merged in 2023-01, with the labels that each got.

#85 actions: use github actions for the linting/UTs
  .ci/Jenkinsfile
  .ci/jobs/defaults.yml
  .ci/jobs/ecs-logging-python-mbp.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
Labels: automation, agent-python, Team:Automation

#86 action: use opentelemetry composite action
  .github/workflows/opentelemetry.yml
Labels: agent-python, Team:Automation

#87 synchronize ecs-logging spec
  tests/resources/spec.json
Labels: automation, agent-python

#89 Update black in pre-commit
  .pre-commit-config.yaml
Labels: agent-python
